### PR TITLE
#58: Error Handling (closes #58)

### LINKED ISSUE #58: Error Handling
[Trello card](https://trello.com/c/586b8e371171617ca67c868a/)

## requirements

The user of the SDK should be able to find out if a request failed because of a network problem, or because the API returned a specific error.

Example of specific errors:

* 403 You don't have the necessary permissions for the resource
* 409 Customer unique constraint violation

## specs

For all API calls, we should reject the Promise with a custom ContactHubError object, like the following one:

```js
{
  status: // the HTTP status code
  message: // the human-readable message returned by the API, or the human-readable message returned by Axios if the API could not be reached
  raw: // the raw error object returned by Axios
}
```

### PR DESCRIPTION
**Pull request by ascariandrea**
Closes #58

### tests performed
Added tests for error handling.
- `npm run e2e`

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: test/e2e/helper.js [hunk 1]
```diff
@@ -1,11 +1,21 @@
...
+type chTestArgumentsType = {
+  token: string,
+  workspaceId: string,
+  nodeId: string
+};
 
-  const token = process.env.CONTACTHUB_TEST_TOKEN;
-  const workspaceId = process.env.CONTACTHUB_TEST_WORKSPACE_ID;
-  const nodeId = process.env.CONTACTHUB_TEST_NODE_ID;
+const chTest = (options: ?chTestArgumentsType): ContactHub => { // eslint-disable-line max-len
```
Comment (dhinus) [inline test/e2e/helper.js]: This is less than 100 chars, no need for `eslint-disable-line max-len`.

File: test/e2e/error.e2e.js [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+
+
+    it('should return a duplicated customer error (409)', async () => {
+      let customer;
+      const customerEmail = 'duplicated-email@fake-customer.com';
+      const customerData = { base: { contacts: { email: customerEmail } } };
+
+      const ch = chTest();
+
+      // try to add a customer for the first time to be sure it's present or fetch it from API
```
Comment (dhinus) [inline test/e2e/error.e2e.js]: If you create a new customer with a random email, then you call `addCustomer` twice you don't need the `query`, the first time it will always succeed, the second time it will always return 409.

**Comment by ascariandrea** [comment]
Added paragraph in `README` and fixed your suggestions 🦌

File: README.md [hunk 3]
```diff
@@ -487,6 +487,32 @@ version of the `Customer`.
...
+
+```js
+{
+  status: 401,
+  message: "The client is not authorized to access the API",
+  raw: { ... } // The axios error object
+}
+```
+
+The `.catch` for Promise has to be defined to catch thrown errors.
```
Comment (dhinus) [inline README.md]: `catch` is not "defined", it is called. I would replace the sentence with:

> You can handle these errors using `.catch()`.

**Comment by ascariandrea** [comment]
Fixed!
